### PR TITLE
Support for 'Deepwoken'

### PR DESCRIPTION
**Pull request by kanenr**
adds proper deepwoken support
really simple for now as i made it within 15 minutes
shows the in-game player name, blood value, armor value, and oath

tried to make the coding style the same as everything prior
thanks

### CODE REVIEW

**Comment by Sem563** [comment]
pasted + detected

**Comment by kanenr** [comment]
> pasted + detected

bro you should have seen what we were doing before to get the player name
`local display_name = humanoid.DisplayName`
`local ingame_name = display_name:match("%b[]\n(%w+ ?%w*)") or display_name:match("(%w+ ?%w*)") or nil`
forgot to check dex to see if leaderstats existed loool

**Comment by Sem563** [comment]
make customteam check guild not lastname

**Review by Sem563 — CHANGES_REQUESTED** [review]
CHANGE CUSTOMTEAM

**Comment by kanenr** [comment]
> CHANGE CUSTOMTEAM

fixed

**Pull request merged**
